### ISSUE TITLE
Allow to customize container options in accessories

### ISSUE THREAD

**Issue by javierav** [mrsked/mrsk#142]
Container options are [supported](https://github.com/mrsked/mrsk#using-container-options) in app containers, also need to be supported in accessories:

```yaml
accessories:
  redis:
    image: redis:latest
    host: 1.1.1.1
    port: "36379:6379"
    options:
      cap-add: true
      cpu-count: 4
    volumes:
      - /var/lib/redis:/data
```
