### ISSUE TITLE
Traefik rule for msultiple roles/destinations on the same server

### ISSUE THREAD

**Issue by tannakartikey** [mrsked/mrsk#190]
I am experimenting with MRSK to deploy multiple environments (i.e. staging, production) of the same app on the same server. 

With `role` and `destination`, deploying the code is straightforward. But if I want to connect two different domains to each container then it's a bit tricky.

At the moment, Traefik rules do not consider role or destination([code](https://github.com/mrsked/mrsk/blob/2146f6d0ecbdc675226daabd5a3dcaa0ce389e0f/lib/mrsk/configuration/role.rb#L76-L83)). As a result, if I don't override Traefik rules, the staging and the production both become part of the same load balancer. Sometimes, the request will go to the staging and sometimes to the production.

I tried to define Traefik service with a different name i.e. `myapp-staging` and `myapp-production` so that I can apply the [Host rule](https://github.com/mrsked/mrsk/blob/2146f6d0ecbdc675226daabd5a3dcaa0ce389e0f/lib/mrsk/configuration/role.rb#L76-L83). But that can not work because the code merges my Traefik rules with ones generated using the `traefik_labels` method. That throws an error on Traefik's side because we can not create multiple services for the same container.

The current workaround I am doing is to use the gem manually where the `traefik_labels` method generates rules as below if the `config.destination` condition is true.
```ruby
{
   "traefik.http.routers.#{config.service}-#{config.destination}.rule" => "PathPrefix(`/`)",
   "traefik.http.services.#{config.service}-#{config.destination}.loadbalancer.healthcheck.path" => config.healthcheck["path"],
   "traefik.http.services.#{config.service}-#{config.destination}.loadbalancer.healthcheck.interval" => "1s",
   "traefik.http.middlewares.#{config.service}-#{config.destination}-retry.retry.attempts" => "5",
   "traefik.http.middlewares.#{config.service}-#{config.destination}-retry.retry.initialinterval" => "500ms",
   "traefik.http.routers.#{config.service}-#{config.destination}.middlewares" => "#{config.service}-#{config.destination}-retry@docker"
}
```

According to me, there are two ways to resolve this.

One:
We allow users to override Traefik rules by providing a flag in the configuration. But it makes things complicated. Since we want this flag only for Traefik related labels.

Two:
 We change the default Traefil labels and make them destination aware. It means that each destination has its own service name and load balancer. We can also include `role` in the format mentioned above e.g.:
 ```
   "traefik.http.routers.#{config.service}-#{config.role}-#{config.destination}.rule" => "PathPrefix(`/`)",
```
The plus side is that each service, with destination and role if available, can be overridden separately.

For reference, dumping relevant part of my config file:

```yml
# config/deploy.yml
service: myapp
image: user/myapp

accessory:
  # db config...
```

```yml
# config/deploy.staging.yml
servers:
  staging:
    traefik: true
    hosts:
      - 8.8.8.8

labels:
  traefik.http.routers.myapp-staging.rule: Host(`staging.myapp.com`)
```

```yml
# config/deploy.production.yml
servers:
  production:
    traefik: true
    hosts:
      - 8.8.8.8

labels:
  traefik.http.routers.myapp-production.rule: Host(`production.myapp.com`)
```

I am using the modified gem where the `traefik_labels` methods use the rule as described above.
