### ISSUE TITLE
Config without web role is not supported

### ISSUE THREAD

**Issue by tannakartikey** [mrsked/mrsk#191]
My config files look as described below. It does not have `web` role. Since I am running everything on a single server, it makes more sense to have the roles defined as `staging` and `production` or `web-staging` and `web-production`.

Here, we need to make the check optional:
https://github.com/mrsked/mrsk/blob/2146f6d0ecbdc675226daabd5a3dcaa0ce389e0f/lib/mrsk/configuration.rb#L82-L84

I think it will affect the `--primary` option if we modify the code to `role(:web)&.primary_host`

My config files:

```yml
# config/deploy.yml
service: myapp
image: user/myapp
```

```yml
# config/deploy.staging.yml
servers:
  staging:
    traefik: true
    hosts:
      - 8.8.8.8
```

```yml
# config/deploy.production.yml
servers:
  production:
    traefik: true
    hosts:
      - 8.8.8.8
```
