### ISSUE TITLE
Removing accessory without confirmation question fails if lock found

### ISSUE THREAD

**Issue by huksley** [mrsked/mrsk#239]
When you want to remove the accessory, for example, `redis` without mrsk asking y/n to confirm, it fails with an unrelated error  if the lock is already found:

```bash
>  mrsk accessory remove redis -y
ERROR: "mrsk lock status" was called with arguments ["-y"]
Usage: "mrsk lock status"
```

To generate a lock which are not automatically removed, you can, for example, try to boot the accessory twice:
```bash
> mrsk accessory boot redis 
> mrsk accessory boot redis 
```

## Ways to reproduce

1. Boot accessory 
2. Try to boot again
3. Try to remove the accessory without confirmation (`mrsk accessory remove redis -y`)

```bash
mrsk accessory boot redis 
mrsk accessory boot redis 
mrsk accessory remove redis -y
```

### Example config

```
accessories:
  redis:
    image: redis:latest
    host: 10.1.1.1
    port: 6379
    volumes:
      - /var/lib/redis:/data
    cmd: "--dir /data"
```
