### ISSUE TITLE
cannot revert back from multi-arch: true to multi-arch: false

### ISSUE THREAD

**Issue by 34code** [mrsked/mrsk#240]
I set up deploy.yml to use a remote builder:
```
builder:
  multiarch: true
  args:
    RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
  remote:
    arch: amd64
    host: ssh://buzz@192.168.5.38
```

then noticed i could shave some seconds of build time by NOT building the arm64 images.. so did this:

```
builder:
  multiarch: false
  args:
    RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
  remote:
    arch: amd64
    host: ssh://buzz@192.168.5.38
```

Now healthcheck seems to fail when deploying.. reverting back to `multi-arch: true` works but build times are longer..
