### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket at

### ISSUE THREAD

**Issue by jasonfb** [mrsked/mrsk#246]
`mrsk deploy`

gives me:

```
  Deploy lock was not released.
  ERROR (SSHKit::Command::Failed): docker exit status: 1
docker stdout: Nothing written
docker stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied
```

This is trying to deploy to an Ubuntu EC2 server on AWS.

I'm not clear about where the error means  — is it telling me it can't connect to my local docker deamon or the docker deamon instance?

I have the Dockerfile copied directly from https://www.driftingruby.com/episodes/deploying-with-mrsk

my deploy file looks like this. 
I think everything is configured the right way now, with DOCKER_USERNAME, DOCKER_PASSWORD and RAILS_MASTER_KEY stored in `.env`.

```
# Name of your application. Used to uniquely configure containers.
service: helios-panoptes

# Name of the container image.
image: jasonheliosdevshop/helios-panoptes

# Deploy to these servers.
servers:
  - 52.91.164.217

registry:
  username:
    - DOCKER_USERNAME
  password:
    - DOCKER_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY


ssh:
  user: ubuntu
```
