### ISSUE TITLE
Allow environment variables as values in deploy.yml

### ISSUE THREAD

**Issue by shafy** [mrsked/mrsk#302]
For example, it would be useful to be able to do something like this in deploy.yml:
```yml
args:
  FOO: ${FOO}
```
where it gets `${FOO}` from the .env file like it does with the secrets. This would work just like it does in a Docker compose config.

Happy to make a PR if this is something you would consider.

**Comment by olivermt** [comment]
<%= ENV["FOO"] %> gives you this already, you can run arbitrary ERB stuff in the yml file :)

**Comment by shafy** [comment]
True. Very facepalm-y of me. Thanks for the reminder @olivermt 😅

**Comment by pythoninthegrass** [comment]
This worked for me too @olivermt. Not as intuitive as docker compose's syntax (probably due to shell expansion), but was able to fill out the `deploy.yml` via
```yaml
service: <%= ENV['SERVICE'] %>

image:
  - <%= ENV['USER_NAME'] %>/<%= ENV['SERVICE'] %>

registry:
  server: <%= ENV['REGISTRY_URL'] %>
  username: <%= ENV['USER_NAME'] %>
  password:
    - KAMAL_REGISTRY_PASSWORD
...
```
Hope that saves future visitors some effort 👌
