### ISSUE TITLE
SSH/Deploy to private VMs with WireGuard

### ISSUE THREAD

**Issue by scart88** [mrsked/mrsk#314]
I can successfully SSH/deploy with MRSK into a private VM inside a Proxmox host using a WireGuard tunnel. 

Is there a better option to do that without Wireguard? 

Thank you!

**Comment by scart88** [comment]
So far the fastest way to setup the Wireguard tunnel was https://www.pivpn.io , however, you need a an additional Public IP assigned to the VM so you can connect from your client (laptop).

edit the `/etc/network/interfaces` in your proxmox host to create a vmbr1 or vmbr2 bridge and assign any subnet to your private VMs (for example: 10.0.0.1/16 or 192.168.10.1/24)

```bash
auto vmbr2
iface vmbr2 inet static
        address 192.168.10.1/24
        bridge-ports none
        bridge-stp off
        bridge-fd 0

        post-up echo 1 > /proc/sys/net/ipv4/ip_forward

        post-up iptables -t nat -A POSTROUTING -s '192.168.10.1/24' -o your-main-network-devce -j MASQUERADE
        post-down iptables -t nat -D POSTROUTING -s '192.168.10.1/24' -o your-main-network-devce -j MASQUERADE
```

![bridge](https://github.com/mrsked/mrsk/assets/84858745/45a19c95-02b0-4e98-921f-4e971058c59c)

Assign a private ip to your VM with the correct gateway so you can have internet access inside your VM.
![vm](https://github.com/mrsked/mrsk/assets/84858745/b6a48e73-dfcb-481b-a17e-40a27dfa2a27)

Once connected to the wireguard tunnel, you can easily ssh to into the private vm `ssh root@192.168.10.10` and use MRSK to deploy your app inside your private VMs.

```yaml
# Name of your application. Used to uniquely configure containers.
service: my-app

# Name of the container image.
image: user/my-app

# Deploy to these servers.
servers:
  - 192.168.10.10
  - 192.168.10.11
```


If you have one additional public IP, you can create load balancer (I used `Caddy` in this example) to reverse proxy to your VMs.

```Caddyfile
my-app.example.com {
  reverse_proxy 192.168.10.10 192.168.10.11 {

    # health_interval 10s
    # health_timeout 5s
  }
}
```

**Comment by scart88** [comment]
After spending more time on this, there is no need for a public IP v4 address to expose the application to the real world.

![proxmox-vms](https://github.com/mrsked/mrsk/assets/84858745/b5da9ab3-f519-4cfc-9a73-b1177c117249)

VM 1000 -> Wireguard setup used to SSH into the the private VMs. This one needs a public IPv4 address.

VM 3030 -> MRSK App 1 -> Private IP: 192.168.10.30
VM 3031 -> MRSK App 2 -> Private IP: 192.168.10.31
VM 3032 -> MRSK DB -> Private IP: 192.168.10.32
VM 3033 -> MRSK Load Balancer -> Private IP: 192.168.10.34


The `deploy.yml` MRSK file is simple and looks like this.

```yaml
service: boxed-app
image: my-user/boxed
servers:
  - 192.168.10.30
  - 192.168.10.31
registry:
  server: registry.gitlab.com 
  username: my-user
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: 192.168.10.32
    REDIS_URL: redis://redis1:6379/1
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
builder:
  local:
    arch: arm64
    host: unix:///Users/<%= `whoami`.strip %>/.docker/run/docker.sock
accessories:
  db:
    image: postgres:15.2
    host: 192.168.10.32
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'boxed'
        POSTGRES_DB: 'boxed'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - pgData:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    host: 192.168.10.32
    port: 6379
    directories:
      - redisData:/data
```


Download Caddy and Cloudflared inside the MRSK Load Balancer VM (3033)

Create a Caddyfile config and reverse proxy to MRSK App 1 and MRSK App 2 vms.

```yaml
:2080 {
        encode zstd gzip
        reverse_proxy 192.168.10.30:80 192.168.10.31:80 {
                #               health_uri /up
                #               health_interval 10s
                #               health_timeout 5s
        }
}
```
Run `caddy start`

Setup cloudflared using their docs https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/

```yaml
url: http://localhost:2080
tunnel: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx [replace this with your tunnel id]
credentials-file: /root/.cloudflared/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx.json
```

run `cloudflared tunnel route dns <UUID or NAME> <hostname>`
and `cloudflared tunnel run <UUID or NAME>`

![cloudflared-dns](https://github.com/mrsked/mrsk/assets/84858745/035fd9ff-3328-4915-a2fa-78708801c0a5)

The app is UP with HTTPS enabled.
![https](https://github.com/mrsked/mrsk/assets/84858745/11345d6b-6598-44be-9320-02f78c7cf1fe)

The login was not working because AssumeSSL is not available in Rails 7.0.5 so I used this https://github.com/mrsked/mrsk/discussions/293 workaround and everything works: 

![cookies](https://github.com/mrsked/mrsk/assets/84858745/a4ab7282-2db6-4076-8463-a272f67c0e8f)

The TTFB is pretty fast too:
![fast](https://github.com/mrsked/mrsk/assets/84858745/fa232ec1-1461-45a7-b433-0106bb6ba91a)


Cloudflared setup is inspired from the Reclaim The Stack https://reclaim-the-stack.com/docs/platform-components/ingress-cloudflared platform where they have the Pros and Cons on using a system like this.
