### ISSUE TITLE
WARNING: No output specified with docker-container driver

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [mrsked/mrsk#322]
First of all, thanks for this gem!!

I am receiving the following error after my docker file builds:
`An image does not exist locally with the tag: pedroaugustorduarte/projects`.

I think the reason is this warning:

`docker stderr: WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load`

Is the some way to add `--load` or `--push` into builder?

my `deploy.yml`:

```yml
# Name of your application. Used to uniquely configure containers.
service: irpf

# Name of the container image.
image: pedroaugustorduarte/projects

# Deploy to these servers.
servers:
  - *****

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: pedroaugustorduarte

  # Always use an access token rather than real password when possible.
  password:
    - MRSK_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    DB_HOST: ***
  secret:
    - RAILS_MASTER_KEY

# Use a different ssh user than root
ssh:
  user: ubuntu

# Configure builder setup.
builder:
  multiarch: false
```

buildx version: github.com/docker/buildx v0.10.5 86bdced7766639d56baa4c7c449a4f6468490f87
mrsk version:  0.13.1
