### ISSUE TITLE
Support optional secrets

### ISSUE THREAD

**Issue by Zeko369** [mrsked/mrsk#359]
(Continuation of #346)

My idea was to somehow override them in the destination files but since they're merged there needs to be a "way" of allowing optional ENVs (without having to do `[empty]` and then check in the app)

### My idea of how this should work

```yml
# deploy.yml
env:
  secret:
    - APP_NAME
    - RETURN_URL?
```

### Cases
1. `APP_NAME` missing -> errors
2. `RETURN_URL` present -> loaded
3. `RETURN_URL` missing -> ignored (so using `ENV['RETURN_URL']` in container would return `nil`)
