### ISSUE TITLE
Build if failing on arm64 when using only local.

### ISSUE THREAD

**Issue by scart88** [mrsked/mrsk#376]
ERROR (ArgumentError): You must specify both local and remote builder config for remote multiarch builds
https://github.com/mrsked/mrsk/blob/main/lib/mrsk/configuration/builder.rb#L87

```yaml
builder:
  local:
    arch: arm64
    host: unix:///Users/<%= `whoami`.strip %>/.docker/run/docker.sock
```
