### ISSUE TITLE
Image build if failing on arm64 when using only local without remote

### ISSUE THREAD

**Issue by scart88** [mrsked/mrsk#377]
Hello

ERROR (ArgumentError): You must specify both local and remote builder config for remote multiarch builds

```yaml
builder:
  local:
    arch: arm64
    host: unix:///Users/<%= `whoami`.strip %>/.docker/run/docker.sock
```

https://github.com/mrsked/mrsk/blob/main/lib/mrsk/configuration/builder.rb#L87

Thank you!
