### ISSUE TITLE
Executing commands on a new container does not start the container with the options defined in the configuration

### ISSUE THREAD

**Issue by brunoprietog** [mrsked/mrsk#388]
I have a configuration like this in my web role to access to the database server, which is not running on the same network as docker, but on the same host.

```yml
servers:
  web:
    hosts:
      - 1.1.1.1
    options:
      add-host: host.docker.internal:host-gateway
```

So, the host becomes host.docker.internal.

When trying to run commands with `mrsk app exec`, the new container that starts does not include these options, so the host is invalid and the application cannot connect to the database.
