### ISSUE TITLE
Docker networking and accessories

### ISSUE THREAD

**Issue by tbuehlmann** [mrsked/mrsk#41]
When having an accessory (like redis or mysql), I'd like to access that from within my app using its docker name (like "my-app-redis"), similar to how it works with docker-compose.

This doesn't work right now as the service and the accessory are both using the default docker network and this kind of hostname resolution/dns only seem to work for user-defined networks. Creating a docker network and using that for services and accessories works, but then traefik won't be able to route traffic to the service without further configuration or connecting traefik to the same network.

Is the idea of creating a shared default docker network for traefik, the service and accessories something we want to pursue in the gem or is this something the user should take care of? A simple `network: <network>` option for deploy.yml would suffice to generate the required `--network` docker args I guess.

**Comment by meceo** [comment]
@tbuehlmann I think I had a similar issue to yours. I try to run mrsk on Synology NAS that has docker installed. Next to web service, I have docker with postgres and redis on the same host. In order to connect web service with the database and Redis one has to add `--add-host=host.docker.internal:host-gateway` to `docker run` command to let the container access the host.
If you look at [the current source code](https://github.com/mrsked/mrsk/blob/main/lib/mrsk/commands/app.rb#L21) you will notice guys take *role.option_args to add to `docker run` command. So configuration like this:

```
servers:
  web:
    hosts:
      - 10.0.0.155
    options:
      "add-host": host.docker.internal:host-gateway
```
does the trick. If you run docker with `--add-host` the `host.docker.internal` will resolve to the container's host IP. From there you can already access the database, Redis, and any other service that is run on the host.

One remark! Currently, mrsk version 0.9.1 is available in RubyGems (`gem install mrsk` gives you that version). However, this version doesn't have `*web.option_args` added to the healthcheck's `docker run` command. It is only available in [master branch](https://github.com/mrsked/mrsk/blob/main/lib/mrsk/commands/healthcheck.rb#L15), so make sure you use the master version. Otherwise, the `mrsk deploy` will still fail.

**Comment by tbuehlmann** [comment]
Right, I thought a networking was a thing with mrsk, but it wasn't. Right now I just use the host's IP address from inside the container and that works well.

**Comment by mike1o1** [comment]
Another option here is to create the docker network yourself by sshing into the machine, and then specify the network name in your deploy.yml. For example:

```yml
servers:
  web:
    hosts:
      - 10.0.1.183
    options:
      "network": "my-network"

traefik:
  options:
    network: "my-network"

accessories:
  db:
    image: postgres:14
    host: 10.0.1.183
    ... etc
    options:
      network: "my-network"
```
