### ISSUE TITLE
Support for periodic task (cron jobs)

### ISSUE THREAD

**Issue by javierav** [mrsked/mrsk#47]
It is usually something common in projects that tasks are executed periodically.

* Heroku recommends the use of clock processes https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes
* Dokku allows you to define tasks in the app.json file https://dokku.com/docs/processes/scheduled-cron-tasks/

What plan is there to do this with mrsk?

**Comment by matharvard** [comment]
I was able to get cron working through [whenever](https://github.com/javan/whenever) on a Rails application:

```
servers:
  web:
    - 0.0.0.0
  whenever:
    hosts:
      - 0.0.0.0
    cmd: "bash -c \"bin/bundle exec whenever --update-crontab && cron -f\""
```

I also needed to ensure that cron was installed in my Dockerfile, as by default using a `ruby:$RUBY_VERSION-slim` image it was not.

**Comment by intrip** [comment]
Can also solve it without using `whenever` in this way:

```yml
servers:
  ...
  cron:
    hosts:
      - 0.0.0.0
    cmd:
      bash -c "cat config/crontab | crontab - && declare -p | grep -Ev '\b(BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID)\b' >> /rails/.cron.env && cron -f"
```

And in `config/crontab`:

```
SHELL=/bin/bash
BASH_ENV=/rails/.cron.env

@weekly  cd /rails && bin/rails runner 'DoSomething' > /proc/1/fd/1 2>&1
```

What it does?

1. Assume you have valid crontab settings in "config/crontab" like the one posted above
2. Replace the current crontab with the new one (if don't want to overwrite can just use ">> /etc/crontab" instead or copy a file in /etc/cron.d, in the last case, the cron needs to mention also the run_as user)
3. expose all shell ENV variables to run the cron
4. starts the cron

**Comment by javierav** [comment]
CRON is an old acquaintance, but it doesn't handle certain problems well, such as working with multiple time zones when launching periodic jobs. I think the best way to manage recurring jobs is Heroku style, using some of the gems that are available in the Ruby ecosystem:

* https://github.com/Rykian/clockwork
* https://github.com/jmettraux/rufus-scheduler
* https://github.com/jjb/ruby-clock
* https://github.com/plashchynski/crono

Example using ruby-clock gem:

```yaml
# config/deploy.yml

servers:
  web:
    - 0.0.0.0
  clock:
    hosts:
      - 0.0.0.0
    cmd: "bin/clock"
```

```ruby
# Clockfile

using RubyClock::DSL

# do something every day, five minutes after midnight
cron '5 0 * * *' do
  DailyActivitySummary.generate_and_send
end
```

**Comment by dhh** [comment]
Closed via https://github.com/mrsked/mrsk/pull/57.

**Comment by sbounmy** [comment]
> servers:
>   web:
>     - 0.0.0.0
>   whenever:
>     hosts:
>       - 0.0.0.0
>     cmd: "bash -c \"bin/bundle exec whenever --update-crontab && cron -f\""

@intrip how did you start cron ?
```sh
cron -f
# cron: can't open or create /var/run/crond.pid: Permission denied
/etc/init.d/cron start
# Starting periodic command scheduler: croncron: can't open or create /var/run/crond.pid: Permission denied failed!
```

PS : I had no error message when `kamal deploy`

**Comment by ronald2wing** [comment]
@sbounmy  Have you resolved the cron issue? Have you tried: https://github.com/javan/whenever/issues/850? The cron status is running but not working for me.

**Comment by ronald2wing** [comment]
> I was able to get cron working through [whenever](https://github.com/javan/whenever) on a Rails application with this deployment configuration:
> 
> ```
> servers:
>   web:
>     - 0.0.0.0
>   whenever:
>     hosts:
>       - 0.0.0.0
>     cmd: "bash -c \"bin/bundle exec whenever --update-crontab && cron -f\""
> ```
> 
> I also needed to ensure that cron was installed in my Dockerfile, as by default using a `ruby:$RUBY_VERSION-slim` image it was not.

I appreciate your help here. I would like to know how you output logs with this setup since this is in a different container.

**Comment by ronald2wing** [comment]
> ```shell
> /var/run/crond.pid
> ```

I have the same error. Have you resolved it yet? I will put these commands in the entrypoint file right now.

**Comment by ronald2wing** [comment]
> > servers:
> > web:
> > - 0.0.0.0
> > whenever:
> > hosts:
> > - 0.0.0.0
> > cmd: "bash -c "bin/bundle exec whenever --update-crontab && cron -f""
> 
> @matharvard how did you start cron ?
> 
> ```shell
> cron -f
> # cron: can't open or create /var/run/crond.pid: Permission denied
> /etc/init.d/cron start
> # Starting periodic command scheduler: croncron: can't open or create /var/run/crond.pid: Permission denied failed!
> ```
> 
> PS : I had no error message when `kamal deploy`
> 
> EDIT: hmm seems like it is not possible to run cron as a non-root user (we use rails in dockerfile / kamal ) https://stackoverflow.com/questions/67493776/the-docker-container-does-not-run-the-crontab

I have the same error. Have you resolved it yet? I will put these commands in the entrypoint file for now.

**Comment by matharvard** [comment]
> > servers:
> > web:
> > - 0.0.0.0
> > whenever:
> > hosts:
> > - 0.0.0.0
> > cmd: "bash -c "bin/bundle exec whenever --update-crontab && cron -f""
> 
> @matharvard how did you start cron ?
> 
> ```shell
> cron -f
> # cron: can't open or create /var/run/crond.pid: Permission denied
> /etc/init.d/cron start
> # Starting periodic command scheduler: croncron: can't open or create /var/run/crond.pid: Permission denied failed!
> ```
> 
> PS : I had no error message when `kamal deploy`
> 
> EDIT: hmm seems like it is not possible to run cron as a non-root user (we use rails in dockerfile / kamal ) https://stackoverflow.com/questions/67493776/the-docker-container-does-not-run-the-crontab

I'm sorry it took me so long to get back to you! The notification email got lost in my inbox. Were you able to figure this out? Your last edit is the key to the solution. I set my `jobs` container to run as root through the options.

```
servers:
  jobs:
    hosts:
      - 100.100.100.100
    cmd: bash -c "bin/bundle exec whenever | crontab - && cron -f"
    options:
      user: root
```
