### ISSUE TITLE
Suggestion: Deploy a docker repository on the server for direct pushes.

### ISSUE THREAD

**Issue by timuckun** [mrsked/mrsk#69]
Some people may want to avoid using third party repositories. It's pretty easy to spin up a repository using docker itself so one idea would be that mrsk would start a repository on the server during deploy, push the container to the repo, then stop the repo.

It could optionally also delete older images based on some strategy (count or age or whatnot).

Just an idea.

**Comment by dhh** [comment]
Feel free to explore it! Like the sound of it.

**Comment by jeremy** [comment]
(Can do `docker save image:tag | gzip | ssh user@host docker load` to schlep an image without a registry. Pretty heavy though; no layers.)

**Comment by timuckun** [comment]
yea but it doesn't seem too difficult to launch a registry using docker itself https://docs.docker.com/registry/deploying/

This way you can keep the layers. 

You can launch the server, do a push, and then shut down the server right away.

**Comment by brapifra** [comment]
Any updates on this? I think the "registry on the server" option sounds reasonable. The image size is [quite small](https://hub.docker.com/_/registry/tags) also.

**Comment by dhh** [comment]
Feel free to investigate 👍. If something simple could be concocted, I could see it being part of MRSK directly. But please do investigate.

**Comment by dotnofoolin** [comment]
I'd really like this as an option. The "where will we store the images/containers and how much will it cost us" question is hard to answer to those that pay the bills.

**Comment by dhh** [comment]
Please do investigate. I think it's going to be rather complicated to have good caching layer dynamics without running a whole docker image repository on the server, and that has a whole rabbit hole of complexity too.

**Comment by dotnofoolin** [comment]
What if we just built the images on the server directly and bypassed a container registry all together? Similar to the `builder` configuration options? I fully understand this negates the benefits of building one container and deploying it multiple places, and would make the overall deploy slower.

**Comment by pingortle** [comment]
I deployed the `registry:2` image using kamal a few days ago. I didn't really need a Dockerfile, but it seemed like kamal only supports deploying with one. It got me thinking… I would love to be able to deploy a public image with kamal. Here's some excerpts.

`Dockerfile`:
```
FROM registry:2

ENV REGISTRY_AUTH="htpasswd"
ENV REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
ENV REGISTRY_AUTH_HTPASSWD_PATH="/auth/htpasswd"

ADD auth/ /auth
```

`config/deploy.yml`
```
service: docker-registry

image: bogus/docker-registry

servers:
  web:
    - x.x.x.x

proxy: 
  ssl: true
  host: docker.example.com
  app_port: 5000
  healthcheck:
    # This is the only path docker hands out unauthenticated 200s
    path: /

  username: bogus
  server: gcr.io

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: arm64

env:
  clear:
    REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
```

As you can see, I could configure auth using env vars, volumes, and an install script to generate creds instead of using the Dockerfile I have today.

If I could remove the Dockerfile, instead specifying a public image to deploy, and omit the push registry, then we'd have a very simple docker registry service we could deploy anywhere and easily use for other kamal apps. Does any of this sound feasible/desirable? I'd be happy to do some legwork to support this use-case.
