### ISSUE TITLE
Allow registry username to be a secret

### ISSUE THREAD

**Issue by kjellberg** [mrsked/mrsk#89]
From DigitalOcean docs:

> For CI systems that support configuring registry authentication via username and password, use a DigitalOcean API **token** as **both the username and the password**. The API token must have read/write privileges to push to your registry.

The username config option should allow a secret reference, the same way as password does. This doesn't work:

```yaml
# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: registry.digitalocean.com
  username: 
    - SECRET_REGISTRY_TOKEN
  password: 
    - SECRET_REGISTRY_TOKEN
```

**Comment by kulturbande** [comment]
That config is working for me:
```
# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: registry.digitalocean.com
  username: <%= ENV.fetch("MRSK_REGISTRY_USER") %>
  password: <%= ENV.fetch("MRSK_REGISTRY_PASSWORD") %>
```
